-- Migration 028: program_deep_analysis
-- Stores versioned deep curriculum analyses (one row per generation).
-- Queries should always filter to the most recent row per specialization_id.

CREATE TABLE IF NOT EXISTS program_deep_analysis (
    id                SERIAL       PRIMARY KEY,
    specialization_id INTEGER      NOT NULL REFERENCES especializaciones(id) ON DELETE CASCADE,
    analysis_json     JSONB        NOT NULL,
    model_version     TEXT         NOT NULL DEFAULT 'gpt-4.1-mini',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Index for the common query: latest analysis per program
CREATE INDEX IF NOT EXISTS idx_pda_specialization_created
    ON program_deep_analysis (specialization_id, created_at DESC);

COMMENT ON TABLE program_deep_analysis IS
    'Versioned deep curriculum analyses generated by curriculum_deep_analysis_engine. '
    'Never updated in place — each generation inserts a new row. '
    'Use ORDER BY created_at DESC LIMIT 1 to fetch the most recent.';
