-- Migration 031: replace run-scoped UNIQUE constraint on ml_program_job_matches
-- with a stable business-key constraint so successive pipeline runs upsert the
-- same row instead of accumulating one row per run_id.
--
-- Background
-- ----------
-- The old constraint was:
--   UNIQUE (run_id, program_document_id, job_document_id, match_method)
-- Because run_id, program_document_id and job_document_id are all new per
-- pipeline execution, ON CONFLICT never fired between runs.  Every re-run
-- appended new rows, leaving stale/degraded scores from earlier runs visible
-- in the dashboard alongside the current ones.
--
-- The new constraint keys on the actual business identity of a match:
--   UNIQUE (especializacion_id, empleo_id, match_method)
-- With this key, the ON CONFLICT … DO UPDATE in save_matches() will overwrite
-- the single canonical row for each program–job–method triple on every run,
-- keeping the table at one current result per pair.
--
-- Columns run_id / program_document_id / job_document_id are retained for
-- audit and lineage purposes but no longer participate in deduplication.
--
-- Pre-condition
-- -------------
-- The table must contain no duplicate (especializacion_id, empleo_id,
-- match_method) triples before this migration runs.  The manual cleanup
-- performed on 2026-09-15 reduced ml_program_job_matches from 16,036 rows to
-- 6,282 rows (0 duplicates remaining) so this ALTER TABLE will succeed without
-- conflicts.  If run on a table that still has duplicates it will fail with
-- "could not create unique index" and must be retried after a dedup pass.

-- Step 1: drop the old run-scoped constraint.
-- The constraint name was generated by PostgreSQL; guard with DO $$ to handle
-- environments where it was already dropped or named differently.
DO $$
DECLARE
    _cname TEXT;
BEGIN
    SELECT conname INTO _cname
    FROM pg_constraint
    WHERE conrelid = 'ml_program_job_matches'::regclass
      AND contype = 'u'
      AND conkey = ARRAY(
            SELECT a.attnum
            FROM pg_attribute a
            WHERE a.attrelid = 'ml_program_job_matches'::regclass
              AND a.attname IN ('run_id', 'program_document_id', 'job_document_id', 'match_method')
              AND NOT a.attisdropped
            ORDER BY a.attnum
          );
    IF _cname IS NOT NULL THEN
        EXECUTE format('ALTER TABLE ml_program_job_matches DROP CONSTRAINT %I', _cname);
        RAISE NOTICE 'Dropped constraint %', _cname;
    ELSE
        RAISE NOTICE 'Old run-scoped constraint not found — already dropped or renamed.';
    END IF;
END $$;

-- Step 2: also drop by the most common auto-generated name as a belt-and-suspenders.
ALTER TABLE ml_program_job_matches
    DROP CONSTRAINT IF EXISTS
        ml_program_job_matches_run_id_program_document_id_job_docu_key;

-- Step 3: add the stable business-key constraint.
ALTER TABLE ml_program_job_matches
    ADD CONSTRAINT uq_match_business_key
    UNIQUE (especializacion_id, empleo_id, match_method);

-- Step 4: supporting index — lookup by program, ordered by score (already
-- exists but recreate to ensure coverage after constraint change).
CREATE INDEX IF NOT EXISTS ix_ml_program_job_matches_program
    ON ml_program_job_matches (especializacion_id, score_match DESC);
